name: afghanioil
description: "A new Flutter project."

publish_to: 'none' # اجعل الحزمة خاصة، احذفها إذا كنت تريد النشر على pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  cloud_firestore: ^5.6.2

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  cached_network_image: ^3.3.1  # تم تحديد الإصدار
  intl: ^0.18.0
  font_awesome_flutter: ^10.8.0
  another_flutter_splash_screen: ^1.2.1
  lottie: ^3.3.0
  full_screen_image: ^2.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.0+3
  photo_view: ^0.15.0
  quickalert: ^1.1.0
  jovial_svg: ^1.1.25
  firebase_core_web: ^2.19.0
  url_launcher: ^6.3.1
  cloud_firestore_web: ^4.4.2
  gif: ^2.3.0
  flash:
  awesome_dialog: ^3.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - image/
    - image/LottieLogo2.json
    - assets/success.gif
    - assets/error.gif
    - assets/warning.gif